import { writeFileSync } from 'node:fs';
import path from 'node:path';
import * as prettier from 'prettier';
import { OUTPUT_DIR, rejectsByColumn, runIngestion } from './pipeline.js';

async function main(): Promise<void> {
  const { sheetRowCount, entries, rejects, provenance } = await runIngestion();

  // The dataset is written as JSON, not a TS array literal: at ~3500+ entries, TypeScript's
  // checker fails with "union type too complex to represent" when a literal this large is
  // checked directly against `ClpReferenceEntry[]`. Importing it as JSON (`resolveJsonModule`)
  // and casting once in the thin wrapper below avoids that — a single cast, not per-element
  // literal-type inference.
  const dataPath = path.join(OUTPUT_DIR, 'annex-vi-data.json');
  writeFileSync(dataPath, JSON.stringify({ provenance, dataset: entries }, null, 2) + '\n');

  const wrapperSource = `/**
 * AUTO-GENERATED by \`npm run ingest:annex-vi\` (src/data/clp-reference/ingestion/run.ts).
 * Do not hand-edit — re-run the ingestion script instead.
 *
 * Source: ${provenance.sourceFile} (Annex VI to CLP Regulation (EC) 1272/2008, ATP${provenance.atpVersion}).
 * Ingested: ${provenance.ingestedAt}.
 * Scope: only the 3 v1 hazard families (acute toxicity oral, skin/eye corrosion, CMR) — most
 * Annex VI rows (physical hazards, aquatic toxicity, STOT, sensitization, non-oral acute-tox
 * routes) are filtered out. See docs/PLAN.md Milestone 2.5 and annex-vi.rejects.json for what
 * was filtered vs. rejected as unparsable.
 *
 * The dataset itself lives in ./annex-vi-data.json (see the comment on \`dataPath\` in
 * pipeline.ts for why) — this file just re-exports it with the engine-facing types attached.
 */
import type { ClpReferenceEntry } from '../../../schemas/clp-reference.js';
import type { AnnexViProvenance } from '../ingestion/types.js';
import data from './annex-vi-data.json';

export const annexViProvenance: AnnexViProvenance = data.provenance;
export const annexViDataset: ClpReferenceEntry[] = data.dataset as ClpReferenceEntry[];
`;

  const outputPath = path.join(OUTPUT_DIR, 'annex-vi.ts');
  const prettierConfig = await prettier.resolveConfig(outputPath);
  const formatted = await prettier.format(wrapperSource, { ...prettierConfig, filepath: outputPath });
  writeFileSync(outputPath, formatted);

  const rejectsPath = path.join(OUTPUT_DIR, 'annex-vi.rejects.json');
  writeFileSync(rejectsPath, JSON.stringify(rejects, null, 2) + '\n');

  console.log(`Annex VI ingestion (ATP${provenance.atpVersion})`);
  console.log(`  sheet rows read:  ${sheetRowCount}`);
  console.log(`  entries emitted:  ${entries.length}`);
  console.log(`  rejects:          ${rejects.length}`, rejectsByColumn(rejects));
  console.log(`  wrote: ${outputPath}`);
  console.log(`  wrote: ${rejectsPath}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
